version: "3.8"

services:

  api-gw:
    build:
      context: .
      dockerfile: Dockerfile-api-gw-v1
    image: ghcr.io/iamfrench/nord-dns_api-gw:latest
    env_file: docker-compose.env
    environment:
      SERVICES: api-gw.v1
      PORT: 3000
    depends_on:
      - nats # service registry
    labels:
      # Docker specific labels https://doc.traefik.io/traefik/routing/providers/docker/#specific-provider-options
      # Explicitly tell Traefik to expose this container
      - traefik.enable=true
      # Allow request only from the predefined entry point named "https"
      - traefik.http.routers.api-gw_Router.entrypoints=https
      # Create rule to match root domain & *.local.{rootDomain}
      - traefik.http.routers.api-gw_Router.rule=HostRegexp(`${APP_DOMAIN_ROOT}`, `{subdomain:[a-z]+}.local.ndns.cf`)
      # Register the service to use for this router
      - traefik.http.routers.api-gw_Router.service=api-gw_Service
      # Use TLS between the Traefik and the api-gw container
      # will terminate the TLS request
      - traefik.http.routers.api-gw_Router.tls=true
      
      # Tell Traefik to use the port 3000 to connect to `api` service
      - traefik.http.services.api-gw_Service.loadbalancer.server.port=3000
      # Tell Traefik to use HTTP2 on HTTP without TLS
      - traefik.http.services.api-gw_Service.loadbalancer.server.scheme=h2c
    deploy:
      resources:
        limits:
          # cpu: 0.25
          memory: 0.5Gb
    networks:
      - internal
  
  redis:
    image: redis:alpine
    entrypoint: redis-server
    networks:
      - internal

  doh:
    build:
      context: .
      dockerfile: Dockerfile-doh-v1
    image: ghcr.io/iamfrench/nord-dns_doh:latest
    env_file: docker-compose.env
    environment:
      SERVICES: doh.v1
    depends_on:
      - nats
      - redis
    labels:
      - traefik.enable=false
    networks:
      - internal

  dot:
    build:
      context: .
      dockerfile: Dockerfile-dot-v1
    image: ghcr.io/iamfrench/nord-dns_dot:latest
    env_file: docker-compose.env
    environment:
      SERVICES: dot.v1
    depends_on:
      - nats
      - redis
    labels:
      - traefik.enable=true
      # TCP config (working, but the service is unavailable (HTTP/503 Service unavailable))
      - traefik.tcp.routers.dot.entrypoints=dot-socket
      - traefik.tcp.routers.dot.rule=HostSNI(`*`)
      - traefik.tcp.routers.dot.service=dotService
      - traefik.tcp.services.dotService.loadbalancer.server.port=853
      - traefik.tcp.routers.dot.tls.passthrough=true
    networks:
      - internal

  filter:
    build:
      context: .
      dockerfile: Dockerfile-filter-v1
    image: ghcr.io/iamfrench/nord-dns_filter:latest
    env_file: docker-compose.env
    environment:
      SERVICES: filter.v1
    depends_on:
      - nats
      - redis
    labels:
      - traefik.enable=false
    networks:
      - internal

  selenium:
    build:
      context: .
      dockerfile: Dockerfile-selenium-v1
      shm_size: '2gb'
    image: ghcr.io/iamfrench/nord-dns_selenium:latest
    env_file: docker-compose.env
    environment:
      SERVICES: selenium.v1
      SELENIUM_SERVER_ENDPOINT: http://selenium-firefox:4444/wd/hub
    depends_on:
      - nats
      - selenium-firefox
    labels:
      - traefik.enable=false
    restart: on-failure
    networks:
      - internal

  selenium-firefox:
    image: selenium/standalone-firefox:4.0.0-beta-1-20210215
    labels:
      - traefik.enable=false
    networks:
      - internal

  nats:
    image: nats:latest
    labels:
      - traefik.enable=false
    networks:
      - internal

  traefik:
    image: traefik:latest
    restart: unless-stopped
    command:
      - --log.level=DEBUG

      ## Disable SSL verification
      # '500 Internal Server Error' caused by: x509: cannot validate certificate for 172.21.0.6 because it doesn't contain any IP SANs
      - --serversTransport.insecureSkipVerify=true


      ## Enabling Docker provider
      - --providers.docker=${TRAEFIK_USE_DOCKER_PROVIDER}
      # Do not expose containers unless explicitly told so
      - --providers.docker.exposedbydefault=false
      # Se the docker daemon endpoint - Default: unix:///var/run/docker.sock
      - --providers.docker.endpoint=${TRAEFIK_DOCKER_ENDPOINT}
      

      ## Enable ECS provider
      - --providers.ecs=${TRAEFIK_USE_ECS_PROVIDER}
      - --providers.ecs.exposedByDefault=false
      - --providers.ecs.autoDiscoverClusters=true
      # - --providers.ecs.region=eu-west-3


      ## Enabling File provider
      - --providers.file.directory=/configuration/
      # Allow Traefik to automatically watch for file changes
      - --providers.file.watch=true


      # Enable Tracing to Jaeger
      - --tracing.jaeger=true
      - --tracing.jaeger.samplingServerURL=http://jaeger:5778/sampling
      - --tracing.jaeger.samplingType=const
      - --tracing.jaeger.samplingParam=1.0
      - --tracing.jaeger.localAgentHostPort=jaeger:6831
      - --tracing.jaeger.propagation=jaeger
      - --tracing.jaeger.traceContextHeaderName=uber-trace-id
      

      ## DoT TLS Socket Entrypoint
      # Traefik will listen to incoming request on entrypoint "dot-socket" to the port 853 (TLS)
      - --entryPoints.dot-socket.address=:853
      

      ## Traefik will listen to incoming request on entrypoint "api-gw" to the port 3001 (HTTPS)
      - --entrypoints.https.address=:3001


      ## Enabling Traefik Dashboard
      - --api.dashboard=true


      ## Enable Prometheus metrics (on port 3000)
      - --metrics.prometheus=true
      - --entryPoints.metrics.address=:3030
      - --metrics.prometheus.entryPoint=metrics
    ports:
      # "external:internal"
      # HTTPS API Gateway
      - ${APP_PORTS_HTTPS}:3001
      # DoT (DNS-over-TLS on port 853)
      - ${APP_PORTS_DOT}:853
    volumes:
      # Bin the certificate folder to use custom certificates
      - ./certificates/:/certificates/:ro
      # Add certificate config for traefik
      - ./certificates/certificates.toml:/configuration/certificates.toml
      - ./traefik.toml:/configuration/traefik.toml
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - traefik.enable=true
      ## Expose Traefik Dashboard
      - traefik.http.routers.dashboard.entrypoints=https
      - traefik.http.routers.dashboard.rule=Host(`${APP_SUBDOMAIN_TRAEFIK}.${APP_DOMAIN_ROOT}`)
      - traefik.http.routers.dashboard.tls=true
      - traefik.http.routers.dashboard.middlewares=traefik-forward-auth
      - traefik.http.routers.dashboard.service=api@internal
    depends_on:
      - jaeger
    networks:
      - internal
      - default
  
  traefik-forward-auth:
    image: thomseddon/traefik-forward-auth:2
    environment:
      - PROVIDERS_GOOGLE_CLIENT_ID=${TRAEFIK_AUTH_PROVIDERS_GOOGLE_CLIENT_ID}
      - PROVIDERS_GOOGLE_CLIENT_SECRET=${TRAEFIK_AUTH_PROVIDERS_GOOGLE_CLIENT_SECRET}
      - SECRET=LnfbuvGezhdP4yRxrdIQ
      - COOKIE_DOMAIN=${APP_DOMAIN_ROOT}
      - URL_PATH=/_oauth
      - AUTH_HOST=${APP_SUBDOMAIN_AUTH}.${APP_DOMAIN_ROOT}:${APP_PORTS_HTTPS}
      # - WHITELIST=
      - DEFAULT_ACTION=auth
      - DEFAULT_PROVIDER=${TRAEFIK_AUTH_DEFAULT_PROVIDER}
      - LOG_LEVEL=debug
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik-forward-auth.entrypoints=https
      - traefik.http.routers.traefik-forward-auth.rule=Host(`${APP_SUBDOMAIN_AUTH}.${APP_DOMAIN_ROOT}`) && PathPrefix(`/_oauth`)
      - traefik.http.routers.traefik-forward-auth.middlewares=traefik-forward-auth
      - traefik.http.routers.traefik-forward-auth.tls=true
      - traefik.http.middlewares.traefik-forward-auth.forwardauth.address=http://traefik-forward-auth:4181
      - traefik.http.middlewares.traefik-forward-auth.forwardauth.authResponseHeaders=X-Forwarded-User
      - traefik.http.services.traefik-forward-auth.loadbalancer.server.port=4181
    depends_on:
      - traefik
    networks:
      - internal

  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    labels:
      - traefik.enable=true
      - traefik.http.routers.jaeger_Router.entrypoints=https
      - traefik.http.routers.jaeger_Router.rule=Host(`${APP_SUBDOMAIN_JAEGER}.${APP_DOMAIN_ROOT}`)
      - traefik.http.routers.jaeger_Router.middlewares=traefik-forward-auth
      - traefik.http.routers.jaeger_Router.tls=true
      - traefik.http.routers.jaeger_Router.service=jaeger_Service
      - traefik.http.services.jaeger_Service.loadbalancer.server.port=16686
    networks:
      - internal
  
  dohjs:
    build:
      context: ./dohjs
    image: ghcr.io/iamfrench/nord-dns_dohjs:latest
    env_file: docker-compose.env
    environment:
      PORT: 3000
    labels:
      - traefik.enable=true
      - traefik.http.routers.dohjs_Router.entrypoints=https
      - traefik.http.routers.dohjs_Router.rule=Host(`${APP_SUBDOMAIN_GUI}.${APP_DOMAIN_ROOT}`)
      - traefik.http.routers.dohjs_Router.service=dohjs_Service
      - traefik.http.routers.dohjs_Router.tls=true
      - traefik.http.services.dohjs_Service.loadbalancer.passhostheader=false
      - traefik.http.services.dohjs_Service.loadbalancer.server.port=3000
      - traefik.http.services.dohjs_Service.loadbalancer.server.scheme=http
      
      # Open Containers Annotations (used for GitHub packages and GitHub Container Registry)
      - org.opencontainers.image.source=https://github.com/IAmFrench/nord-dns
      - org.opencontainers.image.title="DoHjs Web Interface"
      - org.opencontainers.image.description="Provides a Web Interface to test DoH services"
    networks:
      - internal

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - internal
      
  grafana:
    image: grafana/grafana:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.graphana_Router.entrypoints=https
      - traefik.http.routers.graphana_Router.rule=Host(`${APP_SUBDOMAIN_GRAPH}.${APP_DOMAIN_ROOT}`)
      - traefik.http.routers.graphana_Router.middlewares=traefik-forward-auth
      - traefik.http.routers.graphana_Router.tls=true
      - traefik.http.routers.graphana_Router.service=graphana_Service
      - traefik.http.services.graphana_Service.loadbalancer.server.port=3000
    volumes:
      - ./grafana:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - internal

      


networks:
  internal:
  default:
    driver: bridge

# volumes:
#   data:
