FROM node:current-alpine

ENV NODE_ENV=production

RUN mkdir /app
WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install --production

COPY . .

LABEL org.opencontainers.image.source https://github.com/IAmFrench/nord-dns
LABEL org.opencontainers.image.title "DNS-over-TLS Service"
LABEL org.opencontainers.image.description "Responds to DoH (DNS-over-TLS) request using the DoH Service"

CMD ["npm", "start"]
