version: "3.3"

services:

  api:
    build:
      context: .
    image: nord-dns
    env_file: docker-compose.env
    environment:
      SERVICES: api
      PORT: 3000
    depends_on:
      - nats # service registry
      - doh
    labels:
      # Docker specific labels https://doc.traefik.io/traefik/routing/providers/docker/#specific-provider-options
      # Explicitly tell Traefik to expose this container
      - traefik.enable=true
      # Allow request only from the predefined entry point named "api-gw"
      # - traefik.http.routers.api.entrypoints=api-gw
      # - traefik.http.routers.api.rule=HostRegexp(`localhost`, `ndns.cf`, `{subdomain:[a-z]+}.local.ndns.cf`)
      # - traefik.http.routers.api.service=api
      # Use TLS between the API service and Traefik
      # - traefik.http.routers.api.tls=true
      # Tell Traefik to use the port 3000 to connect to `api` service
      # When Traefik Connecting to the Wrong Port: HTTP/502 Gateway Error
      # - traefik.http.services.api.loadbalancer.server.port=3000
      # - traefik.http.services.api.loadBalancer.server.scheme=https

      # TCP config (working, but the service is unavailable (HTTP/503 Service unavailable))
      - traefik.tcp.routers.api.entrypoints=api-gw
      - traefik.tcp.routers.api.rule=HostSNI(`*`)
      - traefik.tcp.routers.api.service=apiService
      - traefik.tcp.services.apiService.loadbalancer.server.port=3000
      - traefik.tcp.routers.api.tls.passthrough=true
    networks:
      - internal
  
  redis:
    image: redis:alpine
    entrypoint: redis-server
    networks:
      - internal

  doh:
    build:
      context: .
    image: nord-dns
    env_file: docker-compose.env
    environment:
      SERVICES: doh.v1
    depends_on:
      - nats
      - redis
    labels:
      # Explicitly tell Traefik to expose this container
      - traefik.enable=true
      # Allow request only from the predefined entry point named "dot-socket"
      - traefik.http.routers.dot.entrypoints=dot-socket
      - traefik.tcp.routers.dot.tls.passthrough=true
      # Tell Traefik to use the port 853 to connect to `dot` service
      - traefik.http.services.dot.loadbalancer.server.port=853
    networks:
      - internal

  dot:
    build:
      context: .
    image: nord-dns
    env_file: docker-compose.env
    environment:
      SERVICES: dot.v1
    depends_on:
      - nats
      - redis
    labels:
      - traefik.enable=true
      # TCP config (working, but the service is unavailable (HTTP/503 Service unavailable))
      - traefik.tcp.routers.dot.entrypoints=dot-socket
      - traefik.tcp.routers.dot.rule=HostSNI(`*`)
      - traefik.tcp.routers.dot.service=dotService
      - traefik.tcp.services.dotService.loadbalancer.server.port=853
      - traefik.tcp.routers.dot.tls.passthrough=true
    networks:
      - internal

  filter:
    build:
      context: .
    image: nord-dns
    env_file: docker-compose.env
    environment:
      SERVICES: filter.v1
    depends_on:
      - nats
      - redis
    labels:
      - traefik.enable=false
    networks:
      - internal

  nats:
    image: nats:latest
    labels:
      - traefik.enable=false
    networks:
      - internal

  traefik:
    image: traefik:latest
    command:
      - --log.level=DEBUG

      # Enabling docker provider
      - --providers.docker=true
      # Do not expose containers unless explicitly told so
      - --providers.docker.exposedbydefault=false

      - --providers.file.directory=/configuration/
      - --providers.file.watch=true

      # Enable Tracing to Jaeger
      - --tracing.jaeger=true
      - --tracing.jaeger.samplingServerURL=http://jaeger:5778/sampling
      - --tracing.jaeger.samplingType=const
      - --tracing.jaeger.samplingParam=1.0
      - --tracing.jaeger.localAgentHostPort=jaeger:6831
      - --tracing.jaeger.propagation=jaeger
      - --tracing.jaeger.traceContextHeaderName=uber-trace-id

      ## API-GW Entrypoint
      # Traefik will listen to incoming request on entrypoint "api-gw" to the port 3001 (HTTPS)
      - --entrypoints.api-gw.address=:3001
      

      ## DoT TLS Socket Entrypoint
      # Traefik will listen to incoming request on entrypoint "dot-socket" to the port 853 (TLS)
      - --entryPoints.dot-socket.address=:853


      ## Jaeger Entrypoint
      # Traefik will listen to incoming request on entrypoint "jaeger" to the port 16686 (HTTPS)
      - --entrypoints.jaeger.address=:16686   
      
      ## Trafik built-in Dashboard
      # http://<Traefik IP>:8080/dashboard/
      - --api.dashboard=true
      - --api.insecure=true
    ports:
      # HTTPS API Gateway (exposed:internal port)
      - 8443:3001
      # DoT (DNS-over-TLS on port 853)
      - 853:853
      # Jaeger Dashboard
      - 16686:16686
      # Trafik built-in Dashboard
      - 8080:8080
    volumes:
      # Bin the certificate folder to use custom certificates
      - ./certificates/:/certificates/:ro
      # Add certificate config for traefik
      - ./certificates/certificates.toml:/configuration/certificates.toml
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - jaeger # for tracing
    networks:
      - internal
      - default
  
  jaeger:
    image: jaegertracing/all-in-one:1.21
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    labels:
      - traefik.enable=true
      # TCP config (working, but the service is unavailable (HTTP/503 Service unavailable))
      - traefik.tcp.routers.jaeger.entrypoints=jaeger
      # Use * to allow non TLS request (https://doc.traefik.io/traefik/v2.0/routing/routers/#rule_1)
      - traefik.tcp.routers.jaeger.rule=HostSNI(`*`)
      - traefik.tcp.routers.jaeger.service=jaeger
      # Don't use TLS
      - traefik.tcp.routers.jaeger.tls=false
      - traefik.tcp.services.jaeger.loadbalancer.server.port=16686
      # - traefik.tcp.routers.jaeger.tls.passthrough=true
    networks:
      - internal

networks:
  internal:

# volumes:
#   data:
