FROM node:current-alpine

ENV NODE_ENV=production

RUN mkdir /app
WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install --production

COPY . .

LABEL org.opencontainers.image.source https://github.com/IAmFrench/nord-dns
LABEL org.opencontainers.image.title "Filter Service"
LABEL org.opencontainers.image.description "Used to filter queries using blocklists such as 1Hosts and EasyList"

CMD ["npm", "start"]
