[http]
  [http.services]
    [http.services.dohjs]
      [http.services.dohjs.loadBalancer]
        [[http.services.dohjs.loadBalancer.servers]]
          url = "https://dohjs.org/"
  [http.routers]
    [http.routers.dohjs]
      entryPoints = ["api-gw"]
      rule = "Host(`gui.ndns.cf`)"
      service = "dohjs@file"
      [http.routers.dohjs.tls]