[[tls.certificates]] #first certificate
   certFile = "/certificates/ndns.cf/cert1.pem" 
   keyFile = "/certificates/ndns.cf/privkey1.key"

[[tls.certificates]] #second certificate
   certFile = "/certificates/local.ndns.cf/cert1.pem" 
   keyFile = "/certificates/local.ndns.cf/privkey1.key"