[[tls.certificates]] #first certificate
   certFile = "/certificates/ndns.cf/fullchain1.pem" 
   keyFile = "/certificates/ndns.cf/privkey1.pem"

[[tls.certificates]] #second certificate
   certFile = "/certificates/local.ndns.cf/fullchain1.pem" 
   keyFile = "/certificates/local.ndns.cf/privkey1.pem"